### ISSUE TITLE
Add simple usage script to readme

### ISSUE THREAD

**Issue by Fafa87** [Fafa87/cellstar#2]

**Comment by rraadd88** [comment]
Hi @Fafa87 ,
Simple usage script to README would be very helpful. I just cloned the repository and I do not know how to use it. :/

**Comment by Fafa87** [comment]
There is Official user guide regarding the usage as CellProfiler plugin but indeed there should be something about using it as python package.

**Comment by PeptideWitch** [comment]
Hey @Fafa87, I'm in the same boat - would love a simple >>load image from file, process, display<< script example 👍

**Comment by Fafa87** [comment]
Added example and code snippet in readme.
